@base = http://localhost:3000
@baseRemote = https://cse341-web-services-z6lg.onrender.com

// get responses from routes.js
get {{base}}/routes/ 

###
get {{base}}/routes/second

###
get {{base}}/routes/third




### list users in DB
get {{base}}/contacts/user

### list a single user (currently hardcoded for ID)
get {{base}}/contacts/username

### list a single user (currently hardcoded to find ID by a given user name)
get {{base}}/contacts/userID

### insert new user to DB
post {{base}}/contacts/writeNewUser HTTP/1.1 content-type: application/json

{
    "firstName":"Mark",
    "lastName":"Adkins",
    "email":"guttermouth@thisispunkrock.com",
    "favoriteColor":"Yellow",
    "birthday":"1968-10-10"
}

###
put {{base}}/contacts/updateUser/68dee6566bd1e3bce944047e HTTP/1.1 content-type: application/json

{
    "firstName":"Jonny",
    "lastName":"Rotten",
    "email":"sexpistols@wepunkers.com",
    "favoriteColor":"Gray",
    "birthday":"1956-01-31"
}

###
delete {{base}}/contacts/deleteUser/68dee6566bd1e3bce944047e



// REMOTE TESTS ON RENDER

###
get {{baseRemote}}

### INSERT new user on Render
post {{baseRemote}}/contacts/writeNewUser

{
    "firstName":"Mark",
    "lastName":"Adkins",
    "email":"guttermouth@thisispunkrock.com",
    "favoriteColor":"Yellow",
    "birthday":"1968-10-10"
}

### UPDATE user on Render
put {{baseRemote}}/contacts/updateUser/68dee6566bd1e3bce944047e

{
    "firstName":"Jonny",
    "lastName":"Rotten",
    "email":"sexpistols@wepunkers.com",
    "favoriteColor":"Gray",
    "birthday":"1956-01-31"
}

### DELETE user on Render
delete {{baseRemote}}/contacts/deleteUser/68dee6566bd1e3bce944047e


